### ISSUE TITLE
java.lang.Exception No files matched regex .*

### ISSUE THREAD

**Issue by dsapoetra** [stianeikeland/bloggr-clj#1]
![screenshot from 2015-02-08 18 08 57](https://cloud.githubusercontent.com/assets/3592714/6096325/aa9df636-afbd-11e4-8ff9-240200ee4550.png)

Hi Stian, i wonder if you could help me as fellow clojurians,
I'm trying to learn how to make a blog (generating static page) and stumble to your blog : http://blog.eikeland.se/2014/04/07/clojure-blog-engine/

Which led me to this repo, but when i try to run it with "lein ring server" it said "java.lang.Exception No files matched regex .\* ", i don't know what happens but so far i only now it's connected to this function : 
(defn load-assets [path](assets/load-assets path [#".*"]))

Will appreciate any advice, thank you!

**Comment by stianeikeland** [comment]
Oh, sorry about that.. the reason this is happening is that it's trying to read /resources/images/*
but I haven't commited the image files to git (as they are quite big). 

I've added some files now so that git keeps the folder https://github.com/stianeikeland/bloggr-clj/commit/21a427fd80b60585f3884428a64ec926e3763edb
(or you could just make /resources/images .. and add a image file)

**Comment by dsapoetra** [comment]
Thank you! Will try it after i'm home.
Thank you for nice repo! Keep lisping
